"""
Django settings for house_rent project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&!&@2zp=e$@4wtv2a@%mn&o8+to$pnl!ac=#x7pw773mmucut$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tolet',
    'bootstrap5',
    'location_field.apps.DefaultConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'house_rent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'house_rent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'productionfiles'

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'mystaticfiles'
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "My Custom Admin",  # Change the title in the browser tab
    "site_header": "Dream Dashboard",  # Change the top-left header
    "site_brand": "CustomBrand",  # Admin panel brand
    "welcome_sign": "Welcome to Dream Admin Panel",  # Welcome message
    "copyright": "ToLet 2024",  # Custom footer copyright text

    # Logo settings
    "site_logo": "your_app/images/logo.png",  # Custom logo path
    "login_logo": "your_app/images/logo.png",  # Logo for the login page
    "login_logo_dark": None,  # Logo for dark theme

    # Topmenu and usermenu links
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},  # Model link
        {"app": "members"},  # App link
    ],

    # Change icons for models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },

    # Add custom sidebar apps
    "related_modal_active": True,  # Enable modals for adding related objects
    "custom_css": None,  # Path to a custom CSS file
    "custom_js": None,  # Path to a custom JavaScript file

    # Show or hide specific app models
    "hide_apps": ["members"],  # Hide specific apps from the sidebar
    "hide_models": ["members.Model"],  # Hide specific models from the sidebar

    # Icons for each app/model in the menu
    "order_with_respect_to": ["auth", "members.Model"],

    # Language bar settings
    "show_language_switch": True,  # Show the language switcher in the admin

    # Top navbar and sidebar settings
    "navigation_expanded": True,  # Keep sidebar expanded by default

    # Add extra permissions
    "extra_permissions": ["members.view_something"],

    # Custom UI settings
    "user_avatar": None,  # Field to use for user avatars
}

LOCATION_FIELD = {
    'provider.google.api': '//maps.google.com/maps/api/js?sensor=false',
    'provider.google.api_key': 'AIzaSyDPqT1cVXmJ5pBXo_oLJgtyq8jj28dMy-k',
    'provider.google.api_libraries': '',
    'provider.google.map.type': 'ROADMAP',
}

# Newslatter
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Example for Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'soheltanvir925@gmail.com'
EMAIL_HOST_PASSWORD = 'vdxgqaomacuyibhv'
DEFAULT_FROM_EMAIL = 'soheltanvir925@gmail.com'


LOGIN_URL = 'login'