# Generated by Django 4.2.16 on 2024-10-14 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tolet', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent_family_flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TOLET', max_length=200)),
                ('images', models.ImageField(upload_to='images/')),
                ('number_of_floor', models.IntegerField()),
                ('total_number_of_room', models.IntegerField()),
                ('number_of_masterbed', models.IntegerField()),
                ('number_of_washroom', models.IntegerField()),
                ('drowing_room', models.BooleanField()),
                ('daining_room', models.BooleanField()),
                ('price', models.IntegerField()),
                ('phone_number', models.CharField(max_length=200)),
                ('rent_date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=200)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('flat_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
