# Generated by Django 4.2.16 on 2024-10-14 05:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tolet', '0003_rent_family_flat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rent_family_flat',
            new_name='family_flat',
        ),
    ]
