# Generated by Django 4.2.16 on 2024-10-14 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tolet', '0004_rename_rent_family_flat_family_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_flat',
            name='gas_electric_bill_attached_price',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family_flat',
            name='lift_facility',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='bachalor_flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TOLET', max_length=200)),
                ('images', models.ImageField(upload_to='images/')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('number_of_floor', models.IntegerField()),
                ('number_of_room', models.IntegerField()),
                ('number_of_seat', models.IntegerField()),
                ('number_of_masterbed', models.BooleanField()),
                ('lift_facility', models.BooleanField()),
                ('gas_electric_bill_attached_price', models.BooleanField()),
                ('washroom_type', models.CharField(choices=[('ATTACH', 'Attach'), ('COMMON', 'Common')], max_length=10)),
                ('food_system', models.CharField(choices=[('Meal', 'meal'), ('Fixed Meal', 'fixed meal')], max_length=20)),
                ('drowing_room', models.BooleanField()),
                ('daining_room', models.BooleanField()),
                ('price_per_room', models.IntegerField()),
                ('price_per_seat', models.IntegerField()),
                ('phone_number', models.CharField(max_length=200)),
                ('rent_date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=200)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('flat_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
