# Generated by Django 4.2.16 on 2024-10-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolet', '0005_family_flat_gas_electric_bill_attached_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bachalor_flat',
            old_name='daining_room',
            new_name='dining_room',
        ),
        migrations.RenameField(
            model_name='bachalor_flat',
            old_name='gas_electric_bill_attached_price',
            new_name='gas_electric_bill_attach_with_price',
        ),
        migrations.RenameField(
            model_name='family_flat',
            old_name='daining_room',
            new_name='dining_room',
        ),
        migrations.RenameField(
            model_name='family_flat',
            old_name='gas_electric_bill_attached_price',
            new_name='gas_electric_bill_attach_with_price',
        ),
        migrations.AddField(
            model_name='family_flat',
            name='gas_system',
            field=models.CharField(choices=[('Cylinder Gas', 'Cylinder Gas'), ('Line Gas', 'Line Gas')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bachalor_flat',
            name='food_system',
            field=models.CharField(choices=[('Meal', 'Meal'), ('Fixed Meal', 'Fixed Meal'), ('Other System', 'Ohter System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bachalor_flat',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bachalor_flat',
            name='price_per_room',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bachalor_flat',
            name='price_per_seat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
