# Generated by Django 4.2.16 on 2024-10-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolet', '0006_rename_daining_room_bachalor_flat_dining_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
